version: '3'

services:
    ctf:
        restart: always
        build: ./
        read_only: true
        ports:
            - '30004:30004'
        volumes:
            - hashcash:/hashcash

volumes:
    hashcash: